name: "PBO Maker"
description: "Action to pack PBOs on self hosted windows runners"


runs:
  using: composite
  steps:
    - name: Install Mikero Tools
      run: |
        echo "Hello World!"
      shell: pwsh