name: "PBO Maker"
description: "Action to pack PBOs on self hosted windows runners"

runs:
  using: composite
  steps:
    - name: Install Mikero Tools
      run: |
        $beforeEventCommit = "${{ github.event.before }}"
        $afterEventCommit = "${{ github.event.after }}"
        $build_tool = "${{ inputs.build_tool }}"
        $private_key = "${{ inputs.private_key }}"
        $projectName = "${{ github.event.repository.name }}"
        $addonPrefix = "${{ inputs.addon_prefix }}"

        Write-Output "Before Event Commit -> $beforeEventCommit"
        Write-Output "After Event Commit -> $afterEventCommit"

        Write-Output "Build Tool -> $build_tool"
        Write-Output "Private Key -> $private_key"

        Write-Output "Project Name -> $projectName"
        Write-Output "Addon Prefix -> $addonPrefix"

        $whereIam = Get-Location
        Write-Output "Where I am -> $whereIam"

        $changedStuff = git diff --stat $beforeCommit $afterCommit
        Write-Output "Changed stuff -> $changedStuff"
        $changedFiles = git diff --name-only $beforeCommit $afterCommit
        if ($changedFiles.Length -eq 0) {
          Write-Output "ERROR: No changed files were found. Aborting."
        }
        Write-Output "Changed Files: $changedFiles"
        $changedDirs = $changedFiles | ForEach-Object { $_.Split('/')[0] } | Select-Object -Unique
        Write-Output "Changed Folders: $changedDirs"

        $symlinkPath = "P:\$projectName"

        if (Test-Path "P:\$projectName" -PathType Leaf) {
          Remove-Item $symlinkPath -Force
          Write-Output "Removing previous leaf symlink: $symlinkPath"
        }

        if (Test-Path $symlinkPath -PathType Container) {
          Remove-Item $symlinkPath -Force
          Write-Output "Removing previous container symlink: $symlinkPath"
        }

        Write-Output "Creating symlink: $symlinkPath"
        $symlinkLink = New-Item -ItemType SymbolicLink -Path "$symlinkPath\" -Target $whereIam

        $changedDirs | ForEach-Object {
          $folder = $_
          $packedDir = "$symlinkPath\${folder}"
          Write-Output "Packing Folder: $packedDir"
        };

        if (Test-Path $symlinkPath -PathType Container) {
          Remove-Item $symlinkPath -Force
          Write-Output "Removing previous container symlink: $symlinkPath"
        }

      shell: pwsh

inputs:
  build_tool:
    description: "Build tool to pack the PBO"
    required: false
    default: "pboproject"
  private_key:
    description: "Private key to sign the PBO"
    required: true
  addon_prefix:
    description: "Addon prefix"
    required: false