name: "PBO Maker"
description: "Action to pack PBOs on self hosted windows runners"

runs:
  using: composite
  steps:
    - name: Install Mikero Tools
      run: |
        echo "${{ inputs.message }}"
      shell: pwsh

inputs:
  message:
    description: "Message to greet"
    required: true