name: "PBO Maker"
description: "Action to pack PBOs on self hosted windows runners"

runs:
  using: composite
  steps:
    - name: Install Mikero Tools
      run: |
        $beforeEventCommit = "${{ github.event.before }}"
        $afterEventCommit = "${{ github.event.after }}"
        $build_tool = "${{ inputs.build_tool }}"
        $private_key = "${{ inputs.private_key }}"
        .\main.ps1
      shell: pwsh

inputs:
  build_tool:
    description: "Build tool to pack the PBO"
    required: false
    default: "pboproject"
  private_key:
    description: "Private key to sign the PBO"
    required: true