name: "PBO Maker"
description: "Action to pack PBOs on self hosted windows runners"

runs:
  using: composite
  steps:
    - name: Install Mikero Tools
      run: |
        Write-Output "Packable Dirs => $packableDirs"

      shell: pwsh

inputs:
  build_tool:
    description: "Build tool to pack the PBO"
    required: false
    default: "pboproject"
  private_key:
    description: "Private key to sign the PBO"
    required: true
  addon_prefix:
    description: "Addon prefix"
    required: false