name: Test PBO Maker actions
on:
  pull_request:
  push:

jobs:
  pack:
    runs-on: windows-latest

    steps:
      - name: Test PBO Maker action
        uses: ./
        with:
          who-to-greet: 'World'