name: Test PBO Maker actions
on:
  pull_request:
  push:

jobs:
  pack:
    runs-on: windows

    steps:
      - name: Set Working Directory
        run: cd ${{ github.workspace }}
        shell: pwsh

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Print Working Directory
        run: pwd
        shell: pwsh

      - name: Print Directory Content
        run: pwd
        shell: pwsh

      - name: Test PBO Maker action
        uses: ./
        with:
          build_tool: 'test build tool'
          private_key: 'test private key'