name: Test PBO Maker actions
on:
  pull_request:
  push:

jobs:
  pack:
    runs-on: windows

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test PBO Maker action
        uses: ./
        with:
          who-to-greet: 'World'