name: Test PBO Maker actions
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Test PBO Maker action
        uses: ./