name: Test PBO Maker actions
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: windows

    steps:
      - name: Test PBO Maker action
        uses: ./
        with:
          who-to-greet: 'World'